channels:
- conda-forge
dependencies:
- python=3.8.5
- pip<=20.1.1
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.0.0
  - numpy==1.24.4
  - psutil==6.0.0
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
